// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/protobuf/wrappers.proto

package com.google.protobuf;

public interface BytesValueOrBuilder extends
        // @@protoc_insertion_point(interface_extends:google.protobuf.BytesValue)
        MessageLiteOrBuilder {

    /**
     * <pre>
     * The bytes value.
     * </pre>
     *
     * <code>bytes value = 1;</code>
     * @return The value.
     */
    ByteString getValue();
}
