// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/protobuf/type.proto

package com.google.protobuf;

/**
 * <pre>
 * Enum value definition.
 * </pre>
 *
 * Protobuf type {@code google.protobuf.EnumValue}
 */
public  final class EnumValue extends
        GeneratedMessageLite<
                EnumValue, EnumValue.Builder> implements
        // @@protoc_insertion_point(message_implements:google.protobuf.EnumValue)
        EnumValueOrBuilder {
    private EnumValue() {
        name_ = "";
        options_ = emptyProtobufList();
    }
    public static final int NAME_FIELD_NUMBER = 1;
    private String name_;
    /**
     * <pre>
     * Enum value name.
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return The name.
     */
    @Override
    public String getName() {
        return name_;
    }
    /**
     * <pre>
     * Enum value name.
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    @Override
    public ByteString
    getNameBytes() {
        return ByteString.copyFromUtf8(name_);
    }
    /**
     * <pre>
     * Enum value name.
     * </pre>
     *
     * <code>string name = 1;</code>
     * @param value The name to set.
     */
    private void setName(
            String value) {
        Class<?> valueClass = value.getClass();

        name_ = value;
    }
    /**
     * <pre>
     * Enum value name.
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    private void clearName() {

        name_ = getDefaultInstance().getName();
    }
    /**
     * <pre>
     * Enum value name.
     * </pre>
     *
     * <code>string name = 1;</code>
     * @param value The bytes for name to set.
     */
    private void setNameBytes(
            ByteString value) {
        checkByteStringIsUtf8(value);
        name_ = value.toStringUtf8();

    }

    public static final int NUMBER_FIELD_NUMBER = 2;
    private int number_;
    /**
     * <pre>
     * Enum value number.
     * </pre>
     *
     * <code>int32 number = 2;</code>
     * @return The number.
     */
    @Override
    public int getNumber() {
        return number_;
    }
    /**
     * <pre>
     * Enum value number.
     * </pre>
     *
     * <code>int32 number = 2;</code>
     * @param value The number to set.
     */
    private void setNumber(int value) {

        number_ = value;
    }
    /**
     * <pre>
     * Enum value number.
     * </pre>
     *
     * <code>int32 number = 2;</code>
     */
    private void clearNumber() {

        number_ = 0;
    }

    public static final int OPTIONS_FIELD_NUMBER = 3;
    private Internal.ProtobufList<Option> options_;
    /**
     * <pre>
     * Protocol buffer options.
     * </pre>
     *
     * <code>repeated .google.protobuf.Option options = 3;</code>
     */
    @Override
    public java.util.List<Option> getOptionsList() {
        return options_;
    }
    /**
     * <pre>
     * Protocol buffer options.
     * </pre>
     *
     * <code>repeated .google.protobuf.Option options = 3;</code>
     */
    public java.util.List<? extends OptionOrBuilder>
    getOptionsOrBuilderList() {
        return options_;
    }
    /**
     * <pre>
     * Protocol buffer options.
     * </pre>
     *
     * <code>repeated .google.protobuf.Option options = 3;</code>
     */
    @Override
    public int getOptionsCount() {
        return options_.size();
    }
    /**
     * <pre>
     * Protocol buffer options.
     * </pre>
     *
     * <code>repeated .google.protobuf.Option options = 3;</code>
     */
    @Override
    public Option getOptions(int index) {
        return options_.get(index);
    }
    /**
     * <pre>
     * Protocol buffer options.
     * </pre>
     *
     * <code>repeated .google.protobuf.Option options = 3;</code>
     */
    public OptionOrBuilder getOptionsOrBuilder(
            int index) {
        return options_.get(index);
    }
    private void ensureOptionsIsMutable() {
        Internal.ProtobufList<Option> tmp = options_;
        if (!tmp.isModifiable()) {
            options_ =
                    GeneratedMessageLite.mutableCopy(tmp);
        }
    }

    /**
     * <pre>
     * Protocol buffer options.
     * </pre>
     *
     * <code>repeated .google.protobuf.Option options = 3;</code>
     */
    private void setOptions(
            int index, Option value) {
        value.getClass();
        ensureOptionsIsMutable();
        options_.set(index, value);
    }
    /**
     * <pre>
     * Protocol buffer options.
     * </pre>
     *
     * <code>repeated .google.protobuf.Option options = 3;</code>
     */
    private void addOptions(Option value) {
        value.getClass();
        ensureOptionsIsMutable();
        options_.add(value);
    }
    /**
     * <pre>
     * Protocol buffer options.
     * </pre>
     *
     * <code>repeated .google.protobuf.Option options = 3;</code>
     */
    private void addOptions(
            int index, Option value) {
        value.getClass();
        ensureOptionsIsMutable();
        options_.add(index, value);
    }
    /**
     * <pre>
     * Protocol buffer options.
     * </pre>
     *
     * <code>repeated .google.protobuf.Option options = 3;</code>
     */
    private void addAllOptions(
            Iterable<? extends Option> values) {
        ensureOptionsIsMutable();
        AbstractMessageLite.addAll(
                values, options_);
    }
    /**
     * <pre>
     * Protocol buffer options.
     * </pre>
     *
     * <code>repeated .google.protobuf.Option options = 3;</code>
     */
    private void clearOptions() {
        options_ = emptyProtobufList();
    }
    /**
     * <pre>
     * Protocol buffer options.
     * </pre>
     *
     * <code>repeated .google.protobuf.Option options = 3;</code>
     */
    private void removeOptions(int index) {
        ensureOptionsIsMutable();
        options_.remove(index);
    }

    public static EnumValue parseFrom(
            java.nio.ByteBuffer data)
            throws InvalidProtocolBufferException {
        return GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data);
    }
    public static EnumValue parseFrom(
            java.nio.ByteBuffer data,
            ExtensionRegistryLite extensionRegistry)
            throws InvalidProtocolBufferException {
        return GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static EnumValue parseFrom(
            ByteString data)
            throws InvalidProtocolBufferException {
        return GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data);
    }
    public static EnumValue parseFrom(
            ByteString data,
            ExtensionRegistryLite extensionRegistry)
            throws InvalidProtocolBufferException {
        return GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static EnumValue parseFrom(byte[] data)
            throws InvalidProtocolBufferException {
        return GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data);
    }
    public static EnumValue parseFrom(
            byte[] data,
            ExtensionRegistryLite extensionRegistry)
            throws InvalidProtocolBufferException {
        return GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static EnumValue parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, input);
    }
    public static EnumValue parseFrom(
            java.io.InputStream input,
            ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static EnumValue parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static EnumValue parseDelimitedFrom(
            java.io.InputStream input,
            ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static EnumValue parseFrom(
            CodedInputStream input)
            throws java.io.IOException {
        return GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, input);
    }
    public static EnumValue parseFrom(
            CodedInputStream input,
            ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
        return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(EnumValue prototype) {
        return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     * Enum value definition.
     * </pre>
     *
     * Protobuf type {@code google.protobuf.EnumValue}
     */
    public static final class Builder extends
            GeneratedMessageLite.Builder<
                    EnumValue, Builder> implements
            // @@protoc_insertion_point(builder_implements:google.protobuf.EnumValue)
            EnumValueOrBuilder {
        // Construct using com.google.protobuf.EnumValue.newBuilder()
        private Builder() {
            super(DEFAULT_INSTANCE);
        }


        /**
         * <pre>
         * Enum value name.
         * </pre>
         *
         * <code>string name = 1;</code>
         * @return The name.
         */
        @Override
        public String getName() {
            return instance.getName();
        }
        /**
         * <pre>
         * Enum value name.
         * </pre>
         *
         * <code>string name = 1;</code>
         * @return The bytes for name.
         */
        @Override
        public ByteString
        getNameBytes() {
            return instance.getNameBytes();
        }
        /**
         * <pre>
         * Enum value name.
         * </pre>
         *
         * <code>string name = 1;</code>
         * @param value The name to set.
         * @return This builder for chaining.
         */
        public Builder setName(
                String value) {
            copyOnWrite();
            instance.setName(value);
            return this;
        }
        /**
         * <pre>
         * Enum value name.
         * </pre>
         *
         * <code>string name = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearName() {
            copyOnWrite();
            instance.clearName();
            return this;
        }
        /**
         * <pre>
         * Enum value name.
         * </pre>
         *
         * <code>string name = 1;</code>
         * @param value The bytes for name to set.
         * @return This builder for chaining.
         */
        public Builder setNameBytes(
                ByteString value) {
            copyOnWrite();
            instance.setNameBytes(value);
            return this;
        }

        /**
         * <pre>
         * Enum value number.
         * </pre>
         *
         * <code>int32 number = 2;</code>
         * @return The number.
         */
        @Override
        public int getNumber() {
            return instance.getNumber();
        }
        /**
         * <pre>
         * Enum value number.
         * </pre>
         *
         * <code>int32 number = 2;</code>
         * @param value The number to set.
         * @return This builder for chaining.
         */
        public Builder setNumber(int value) {
            copyOnWrite();
            instance.setNumber(value);
            return this;
        }
        /**
         * <pre>
         * Enum value number.
         * </pre>
         *
         * <code>int32 number = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearNumber() {
            copyOnWrite();
            instance.clearNumber();
            return this;
        }

        /**
         * <pre>
         * Protocol buffer options.
         * </pre>
         *
         * <code>repeated .google.protobuf.Option options = 3;</code>
         */
        @Override
        public java.util.List<Option> getOptionsList() {
            return java.util.Collections.unmodifiableList(
                    instance.getOptionsList());
        }
        /**
         * <pre>
         * Protocol buffer options.
         * </pre>
         *
         * <code>repeated .google.protobuf.Option options = 3;</code>
         */
        @Override
        public int getOptionsCount() {
            return instance.getOptionsCount();
        }/**
         * <pre>
         * Protocol buffer options.
         * </pre>
         *
         * <code>repeated .google.protobuf.Option options = 3;</code>
         */
        @Override
        public Option getOptions(int index) {
            return instance.getOptions(index);
        }
        /**
         * <pre>
         * Protocol buffer options.
         * </pre>
         *
         * <code>repeated .google.protobuf.Option options = 3;</code>
         */
        public Builder setOptions(
                int index, Option value) {
            copyOnWrite();
            instance.setOptions(index, value);
            return this;
        }
        /**
         * <pre>
         * Protocol buffer options.
         * </pre>
         *
         * <code>repeated .google.protobuf.Option options = 3;</code>
         */
        public Builder setOptions(
                int index, Option.Builder builderForValue) {
            copyOnWrite();
            instance.setOptions(index,
                    builderForValue.build());
            return this;
        }
        /**
         * <pre>
         * Protocol buffer options.
         * </pre>
         *
         * <code>repeated .google.protobuf.Option options = 3;</code>
         */
        public Builder addOptions(Option value) {
            copyOnWrite();
            instance.addOptions(value);
            return this;
        }
        /**
         * <pre>
         * Protocol buffer options.
         * </pre>
         *
         * <code>repeated .google.protobuf.Option options = 3;</code>
         */
        public Builder addOptions(
                int index, Option value) {
            copyOnWrite();
            instance.addOptions(index, value);
            return this;
        }
        /**
         * <pre>
         * Protocol buffer options.
         * </pre>
         *
         * <code>repeated .google.protobuf.Option options = 3;</code>
         */
        public Builder addOptions(
                Option.Builder builderForValue) {
            copyOnWrite();
            instance.addOptions(builderForValue.build());
            return this;
        }
        /**
         * <pre>
         * Protocol buffer options.
         * </pre>
         *
         * <code>repeated .google.protobuf.Option options = 3;</code>
         */
        public Builder addOptions(
                int index, Option.Builder builderForValue) {
            copyOnWrite();
            instance.addOptions(index,
                    builderForValue.build());
            return this;
        }
        /**
         * <pre>
         * Protocol buffer options.
         * </pre>
         *
         * <code>repeated .google.protobuf.Option options = 3;</code>
         */
        public Builder addAllOptions(
                Iterable<? extends Option> values) {
            copyOnWrite();
            instance.addAllOptions(values);
            return this;
        }
        /**
         * <pre>
         * Protocol buffer options.
         * </pre>
         *
         * <code>repeated .google.protobuf.Option options = 3;</code>
         */
        public Builder clearOptions() {
            copyOnWrite();
            instance.clearOptions();
            return this;
        }
        /**
         * <pre>
         * Protocol buffer options.
         * </pre>
         *
         * <code>repeated .google.protobuf.Option options = 3;</code>
         */
        public Builder removeOptions(int index) {
            copyOnWrite();
            instance.removeOptions(index);
            return this;
        }

        // @@protoc_insertion_point(builder_scope:google.protobuf.EnumValue)
    }
    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
            MethodToInvoke method,
            Object arg0, Object arg1) {
        switch (method) {
            case NEW_MUTABLE_INSTANCE: {
                return new EnumValue();
            }
            case NEW_BUILDER: {
                return new Builder();
            }
            case BUILD_MESSAGE_INFO: {
                Object[] objects = new Object[] {
                        "name_",
                        "number_",
                        "options_",
                        Option.class,
                };
                String info =
                        "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0001\u0000\u0001\u0208\u0002\u0004" +
                                "\u0003\u001b";
                return newMessageInfo(DEFAULT_INSTANCE, info, objects);
            }
            // fall through
            case GET_DEFAULT_INSTANCE: {
                return DEFAULT_INSTANCE;
            }
            case GET_PARSER: {
                Parser<EnumValue> parser = PARSER;
                if (parser == null) {
                    synchronized (EnumValue.class) {
                        parser = PARSER;
                        if (parser == null) {
                            parser =
                                    new DefaultInstanceBasedParser<EnumValue>(
                                            DEFAULT_INSTANCE);
                            PARSER = parser;
                        }
                    }
                }
                return parser;
            }
            case GET_MEMOIZED_IS_INITIALIZED: {
                return (byte) 1;
            }
            case SET_MEMOIZED_IS_INITIALIZED: {
                return null;
            }
        }
        throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:google.protobuf.EnumValue)
    private static final EnumValue DEFAULT_INSTANCE;
    static {
        EnumValue defaultInstance = new EnumValue();
        // New instances are implicitly immutable so no need to make
        // immutable.
        DEFAULT_INSTANCE = defaultInstance;
        GeneratedMessageLite.registerDefaultInstance(
                EnumValue.class, defaultInstance);
    }

    public static EnumValue getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static volatile Parser<EnumValue> PARSER;

    public static Parser<EnumValue> parser() {
        return DEFAULT_INSTANCE.getParserForType();
    }
}

