// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/protobuf/type.proto

package com.google.protobuf;

public interface EnumOrBuilder extends
        // @@protoc_insertion_point(interface_extends:google.protobuf.Enum)
        MessageLiteOrBuilder {

    /**
     * <pre>
     * Enum type name.
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return The name.
     */
    String getName();
    /**
     * <pre>
     * Enum type name.
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    ByteString
    getNameBytes();

    /**
     * <pre>
     * Enum value definitions.
     * </pre>
     *
     * <code>repeated .google.protobuf.EnumValue enumvalue = 2;</code>
     */
    java.util.List<EnumValue>
    getEnumvalueList();
    /**
     * <pre>
     * Enum value definitions.
     * </pre>
     *
     * <code>repeated .google.protobuf.EnumValue enumvalue = 2;</code>
     */
    EnumValue getEnumvalue(int index);
    /**
     * <pre>
     * Enum value definitions.
     * </pre>
     *
     * <code>repeated .google.protobuf.EnumValue enumvalue = 2;</code>
     */
    int getEnumvalueCount();

    /**
     * <pre>
     * Protocol buffer options.
     * </pre>
     *
     * <code>repeated .google.protobuf.Option options = 3;</code>
     */
    java.util.List<Option>
    getOptionsList();
    /**
     * <pre>
     * Protocol buffer options.
     * </pre>
     *
     * <code>repeated .google.protobuf.Option options = 3;</code>
     */
    Option getOptions(int index);
    /**
     * <pre>
     * Protocol buffer options.
     * </pre>
     *
     * <code>repeated .google.protobuf.Option options = 3;</code>
     */
    int getOptionsCount();

    /**
     * <pre>
     * The source context.
     * </pre>
     *
     * <code>.google.protobuf.SourceContext source_context = 4;</code>
     * @return Whether the sourceContext field is set.
     */
    boolean hasSourceContext();
    /**
     * <pre>
     * The source context.
     * </pre>
     *
     * <code>.google.protobuf.SourceContext source_context = 4;</code>
     * @return The sourceContext.
     */
    SourceContext getSourceContext();

    /**
     * <pre>
     * The source syntax.
     * </pre>
     *
     * <code>.google.protobuf.Syntax syntax = 5;</code>
     * @return The enum numeric value on the wire for syntax.
     */
    int getSyntaxValue();
    /**
     * <pre>
     * The source syntax.
     * </pre>
     *
     * <code>.google.protobuf.Syntax syntax = 5;</code>
     * @return The syntax.
     */
    Syntax getSyntax();
}
