// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/protobuf/struct.proto

package com.google.protobuf;

public interface ListValueOrBuilder extends
        // @@protoc_insertion_point(interface_extends:google.protobuf.ListValue)
        MessageLiteOrBuilder {

    /**
     * <pre>
     * Repeated field of dynamically typed values.
     * </pre>
     *
     * <code>repeated .google.protobuf.Value values = 1;</code>
     */
    java.util.List<Value>
    getValuesList();
    /**
     * <pre>
     * Repeated field of dynamically typed values.
     * </pre>
     *
     * <code>repeated .google.protobuf.Value values = 1;</code>
     */
    Value getValues(int index);
    /**
     * <pre>
     * Repeated field of dynamically typed values.
     * </pre>
     *
     * <code>repeated .google.protobuf.Value values = 1;</code>
     */
    int getValuesCount();
}
