// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/protobuf/source_context.proto

package com.google.protobuf;

public interface SourceContextOrBuilder extends
        // @@protoc_insertion_point(interface_extends:google.protobuf.SourceContext)
        MessageLiteOrBuilder {

    /**
     * <pre>
     * The path-qualified name of the .proto file that contained the associated
     * protobuf element.  For example: `"google/protobuf/source_context.proto"`.
     * </pre>
     *
     * <code>string file_name = 1;</code>
     * @return The fileName.
     */
    String getFileName();
    /**
     * <pre>
     * The path-qualified name of the .proto file that contained the associated
     * protobuf element.  For example: `"google/protobuf/source_context.proto"`.
     * </pre>
     *
     * <code>string file_name = 1;</code>
     * @return The bytes for fileName.
     */
    ByteString
    getFileNameBytes();
}
