// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/protobuf/wrappers.proto

package com.google.protobuf;

public interface StringValueOrBuilder extends
        // @@protoc_insertion_point(interface_extends:google.protobuf.StringValue)
        MessageLiteOrBuilder {

    /**
     * <pre>
     * The string value.
     * </pre>
     *
     * <code>string value = 1;</code>
     * @return The value.
     */
    String getValue();
    /**
     * <pre>
     * The string value.
     * </pre>
     *
     * <code>string value = 1;</code>
     * @return The bytes for value.
     */
    ByteString
    getValueBytes();
}
