// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/protobuf/wrappers.proto

package com.google.protobuf;

/**
 * <pre>
 * Wrapper message for `string`.
 * The JSON representation for `StringValue` is JSON string.
 * </pre>
 *
 * Protobuf type {@code google.protobuf.StringValue}
 */
public  final class StringValue extends
        GeneratedMessageLite<
                StringValue, StringValue.Builder> implements
        // @@protoc_insertion_point(message_implements:google.protobuf.StringValue)
        StringValueOrBuilder {
    private StringValue() {
        value_ = "";
    }
    public static final int VALUE_FIELD_NUMBER = 1;
    private String value_;
    /**
     * <pre>
     * The string value.
     * </pre>
     *
     * <code>string value = 1;</code>
     * @return The value.
     */
    @Override
    public String getValue() {
        return value_;
    }
    /**
     * <pre>
     * The string value.
     * </pre>
     *
     * <code>string value = 1;</code>
     * @return The bytes for value.
     */
    @Override
    public ByteString
    getValueBytes() {
        return ByteString.copyFromUtf8(value_);
    }
    /**
     * <pre>
     * The string value.
     * </pre>
     *
     * <code>string value = 1;</code>
     * @param value The value to set.
     */
    private void setValue(
            String value) {
        Class<?> valueClass = value.getClass();

        value_ = value;
    }
    /**
     * <pre>
     * The string value.
     * </pre>
     *
     * <code>string value = 1;</code>
     */
    private void clearValue() {

        value_ = getDefaultInstance().getValue();
    }
    /**
     * <pre>
     * The string value.
     * </pre>
     *
     * <code>string value = 1;</code>
     * @param value The bytes for value to set.
     */
    private void setValueBytes(
            ByteString value) {
        checkByteStringIsUtf8(value);
        value_ = value.toStringUtf8();

    }

    public static StringValue parseFrom(
            java.nio.ByteBuffer data)
            throws InvalidProtocolBufferException {
        return GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data);
    }
    public static StringValue parseFrom(
            java.nio.ByteBuffer data,
            ExtensionRegistryLite extensionRegistry)
            throws InvalidProtocolBufferException {
        return GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static StringValue parseFrom(
            ByteString data)
            throws InvalidProtocolBufferException {
        return GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data);
    }
    public static StringValue parseFrom(
            ByteString data,
            ExtensionRegistryLite extensionRegistry)
            throws InvalidProtocolBufferException {
        return GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static StringValue parseFrom(byte[] data)
            throws InvalidProtocolBufferException {
        return GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data);
    }
    public static StringValue parseFrom(
            byte[] data,
            ExtensionRegistryLite extensionRegistry)
            throws InvalidProtocolBufferException {
        return GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static StringValue parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, input);
    }
    public static StringValue parseFrom(
            java.io.InputStream input,
            ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static StringValue parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static StringValue parseDelimitedFrom(
            java.io.InputStream input,
            ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static StringValue parseFrom(
            CodedInputStream input)
            throws java.io.IOException {
        return GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, input);
    }
    public static StringValue parseFrom(
            CodedInputStream input,
            ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
        return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(StringValue prototype) {
        return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     * Wrapper message for `string`.
     * The JSON representation for `StringValue` is JSON string.
     * </pre>
     *
     * Protobuf type {@code google.protobuf.StringValue}
     */
    public static final class Builder extends
            GeneratedMessageLite.Builder<
                    StringValue, Builder> implements
            // @@protoc_insertion_point(builder_implements:google.protobuf.StringValue)
            StringValueOrBuilder {
        // Construct using com.google.protobuf.StringValue.newBuilder()
        private Builder() {
            super(DEFAULT_INSTANCE);
        }


        /**
         * <pre>
         * The string value.
         * </pre>
         *
         * <code>string value = 1;</code>
         * @return The value.
         */
        @Override
        public String getValue() {
            return instance.getValue();
        }
        /**
         * <pre>
         * The string value.
         * </pre>
         *
         * <code>string value = 1;</code>
         * @return The bytes for value.
         */
        @Override
        public ByteString
        getValueBytes() {
            return instance.getValueBytes();
        }
        /**
         * <pre>
         * The string value.
         * </pre>
         *
         * <code>string value = 1;</code>
         * @param value The value to set.
         * @return This builder for chaining.
         */
        public Builder setValue(
                String value) {
            copyOnWrite();
            instance.setValue(value);
            return this;
        }
        /**
         * <pre>
         * The string value.
         * </pre>
         *
         * <code>string value = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearValue() {
            copyOnWrite();
            instance.clearValue();
            return this;
        }
        /**
         * <pre>
         * The string value.
         * </pre>
         *
         * <code>string value = 1;</code>
         * @param value The bytes for value to set.
         * @return This builder for chaining.
         */
        public Builder setValueBytes(
                ByteString value) {
            copyOnWrite();
            instance.setValueBytes(value);
            return this;
        }

        // @@protoc_insertion_point(builder_scope:google.protobuf.StringValue)
    }
    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
            MethodToInvoke method,
            Object arg0, Object arg1) {
        switch (method) {
            case NEW_MUTABLE_INSTANCE: {
                return new StringValue();
            }
            case NEW_BUILDER: {
                return new Builder();
            }
            case BUILD_MESSAGE_INFO: {
                Object[] objects = new Object[] {
                        "value_",
                };
                String info =
                        "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u0208";
                return newMessageInfo(DEFAULT_INSTANCE, info, objects);
            }
            // fall through
            case GET_DEFAULT_INSTANCE: {
                return DEFAULT_INSTANCE;
            }
            case GET_PARSER: {
                Parser<StringValue> parser = PARSER;
                if (parser == null) {
                    synchronized (StringValue.class) {
                        parser = PARSER;
                        if (parser == null) {
                            parser =
                                    new DefaultInstanceBasedParser<StringValue>(
                                            DEFAULT_INSTANCE);
                            PARSER = parser;
                        }
                    }
                }
                return parser;
            }
            case GET_MEMOIZED_IS_INITIALIZED: {
                return (byte) 1;
            }
            case SET_MEMOIZED_IS_INITIALIZED: {
                return null;
            }
        }
        throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:google.protobuf.StringValue)
    private static final StringValue DEFAULT_INSTANCE;
    static {
        StringValue defaultInstance = new StringValue();
        // New instances are implicitly immutable so no need to make
        // immutable.
        DEFAULT_INSTANCE = defaultInstance;
        GeneratedMessageLite.registerDefaultInstance(
                StringValue.class, defaultInstance);
    }

    public static StringValue getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    public static StringValue of(String value) {
        return newBuilder().setValue(value).build();
    }

    private static volatile Parser<StringValue> PARSER;

    public static Parser<StringValue> parser() {
        return DEFAULT_INSTANCE.getParserForType();
    }
}

