// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/protobuf/type.proto

package com.google.protobuf;

public interface TypeOrBuilder extends
        // @@protoc_insertion_point(interface_extends:google.protobuf.Type)
        MessageLiteOrBuilder {

    /**
     * <pre>
     * The fully qualified message name.
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return The name.
     */
    String getName();
    /**
     * <pre>
     * The fully qualified message name.
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    ByteString
    getNameBytes();

    /**
     * <pre>
     * The list of fields.
     * </pre>
     *
     * <code>repeated .google.protobuf.Field fields = 2;</code>
     */
    java.util.List<Field>
    getFieldsList();
    /**
     * <pre>
     * The list of fields.
     * </pre>
     *
     * <code>repeated .google.protobuf.Field fields = 2;</code>
     */
    Field getFields(int index);
    /**
     * <pre>
     * The list of fields.
     * </pre>
     *
     * <code>repeated .google.protobuf.Field fields = 2;</code>
     */
    int getFieldsCount();

    /**
     * <pre>
     * The list of types appearing in `oneof` definitions in this type.
     * </pre>
     *
     * <code>repeated string oneofs = 3;</code>
     * @return A list containing the oneofs.
     */
    java.util.List<String>
    getOneofsList();
    /**
     * <pre>
     * The list of types appearing in `oneof` definitions in this type.
     * </pre>
     *
     * <code>repeated string oneofs = 3;</code>
     * @return The count of oneofs.
     */
    int getOneofsCount();
    /**
     * <pre>
     * The list of types appearing in `oneof` definitions in this type.
     * </pre>
     *
     * <code>repeated string oneofs = 3;</code>
     * @param index The index of the element to return.
     * @return The oneofs at the given index.
     */
    String getOneofs(int index);
    /**
     * <pre>
     * The list of types appearing in `oneof` definitions in this type.
     * </pre>
     *
     * <code>repeated string oneofs = 3;</code>
     * @param index The index of the element to return.
     * @return The oneofs at the given index.
     */
    ByteString
    getOneofsBytes(int index);

    /**
     * <pre>
     * The protocol buffer options.
     * </pre>
     *
     * <code>repeated .google.protobuf.Option options = 4;</code>
     */
    java.util.List<Option>
    getOptionsList();
    /**
     * <pre>
     * The protocol buffer options.
     * </pre>
     *
     * <code>repeated .google.protobuf.Option options = 4;</code>
     */
    Option getOptions(int index);
    /**
     * <pre>
     * The protocol buffer options.
     * </pre>
     *
     * <code>repeated .google.protobuf.Option options = 4;</code>
     */
    int getOptionsCount();

    /**
     * <pre>
     * The source context.
     * </pre>
     *
     * <code>.google.protobuf.SourceContext source_context = 5;</code>
     * @return Whether the sourceContext field is set.
     */
    boolean hasSourceContext();
    /**
     * <pre>
     * The source context.
     * </pre>
     *
     * <code>.google.protobuf.SourceContext source_context = 5;</code>
     * @return The sourceContext.
     */
    SourceContext getSourceContext();

    /**
     * <pre>
     * The source syntax.
     * </pre>
     *
     * <code>.google.protobuf.Syntax syntax = 6;</code>
     * @return The enum numeric value on the wire for syntax.
     */
    int getSyntaxValue();
    /**
     * <pre>
     * The source syntax.
     * </pre>
     *
     * <code>.google.protobuf.Syntax syntax = 6;</code>
     * @return The syntax.
     */
    Syntax getSyntax();
}
