// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/protobuf/struct.proto

package com.google.protobuf;

/**
 * <pre>
 * `Value` represents a dynamically typed value which can be either
 * null, a number, a string, a boolean, a recursive struct value, or a
 * list of values. A producer of value is expected to set one of these
 * variants. Absence of any variant indicates an error.
 * The JSON representation for `Value` is JSON value.
 * </pre>
 *
 * Protobuf type {@code google.protobuf.Value}
 */
public  final class Value extends
        GeneratedMessageLite<
                Value, Value.Builder> implements
        // @@protoc_insertion_point(message_implements:google.protobuf.Value)
        ValueOrBuilder {
    private Value() {
    }
    private int kindCase_ = 0;
    private Object kind_;
    public enum KindCase {
        NULL_VALUE(1),
        NUMBER_VALUE(2),
        STRING_VALUE(3),
        BOOL_VALUE(4),
        STRUCT_VALUE(5),
        LIST_VALUE(6),
        KIND_NOT_SET(0);
        private final int value;
        private KindCase(int value) {
            this.value = value;
        }
        /**
         * @deprecated Use {@link #forNumber(int)} instead.
         */
        @Deprecated
        public static KindCase valueOf(int value) {
            return forNumber(value);
        }

        public static KindCase forNumber(int value) {
            switch (value) {
                case 1: return NULL_VALUE;
                case 2: return NUMBER_VALUE;
                case 3: return STRING_VALUE;
                case 4: return BOOL_VALUE;
                case 5: return STRUCT_VALUE;
                case 6: return LIST_VALUE;
                case 0: return KIND_NOT_SET;
                default: return null;
            }
        }
        public int getNumber() {
            return this.value;
        }
    };

    @Override
    public KindCase
    getKindCase() {
        return KindCase.forNumber(
                kindCase_);
    }

    private void clearKind() {
        kindCase_ = 0;
        kind_ = null;
    }

    public static final int NULL_VALUE_FIELD_NUMBER = 1;
    /**
     * <pre>
     * Represents a null value.
     * </pre>
     *
     * <code>.google.protobuf.NullValue null_value = 1;</code>
     * @return Whether the nullValue field is set.
     */
    @Override
    public boolean hasNullValue() {
        return kindCase_ == 1;
    }
    /**
     * <pre>
     * Represents a null value.
     * </pre>
     *
     * <code>.google.protobuf.NullValue null_value = 1;</code>
     * @return The enum numeric value on the wire for nullValue.
     */
    @Override
    public int getNullValueValue() {
        if (kindCase_ == 1) {
            return (Integer) kind_;
        }
        return 0;
    }
    /**
     * <pre>
     * Represents a null value.
     * </pre>
     *
     * <code>.google.protobuf.NullValue null_value = 1;</code>
     * @return The nullValue.
     */
    @Override
    public NullValue getNullValue() {
        if (kindCase_ == 1) {
            NullValue result = NullValue.forNumber((Integer) kind_);
            return result == null ? NullValue.UNRECOGNIZED : result;
        }
        return NullValue.NULL_VALUE;
    }
    /**
     * <pre>
     * Represents a null value.
     * </pre>
     *
     * <code>.google.protobuf.NullValue null_value = 1;</code>
     * @param value The enum numeric value on the wire for nullValue to set.
     */
    private void setNullValueValue(int value) {
        kindCase_ = 1;
        kind_ = value;
    }
    /**
     * <pre>
     * Represents a null value.
     * </pre>
     *
     * <code>.google.protobuf.NullValue null_value = 1;</code>
     * @param value The nullValue to set.
     */
    private void setNullValue(NullValue value) {
        kind_ = value.getNumber();
        kindCase_ = 1;
    }
    /**
     * <pre>
     * Represents a null value.
     * </pre>
     *
     * <code>.google.protobuf.NullValue null_value = 1;</code>
     */
    private void clearNullValue() {
        if (kindCase_ == 1) {
            kindCase_ = 0;
            kind_ = null;
        }
    }

    public static final int NUMBER_VALUE_FIELD_NUMBER = 2;
    /**
     * <pre>
     * Represents a double value.
     * </pre>
     *
     * <code>double number_value = 2;</code>
     * @return Whether the numberValue field is set.
     */
    @Override
    public boolean hasNumberValue() {
        return kindCase_ == 2;
    }
    /**
     * <pre>
     * Represents a double value.
     * </pre>
     *
     * <code>double number_value = 2;</code>
     * @return The numberValue.
     */
    @Override
    public double getNumberValue() {
        if (kindCase_ == 2) {
            return (Double) kind_;
        }
        return 0D;
    }
    /**
     * <pre>
     * Represents a double value.
     * </pre>
     *
     * <code>double number_value = 2;</code>
     * @param value The numberValue to set.
     */
    private void setNumberValue(double value) {
        kindCase_ = 2;
        kind_ = value;
    }
    /**
     * <pre>
     * Represents a double value.
     * </pre>
     *
     * <code>double number_value = 2;</code>
     */
    private void clearNumberValue() {
        if (kindCase_ == 2) {
            kindCase_ = 0;
            kind_ = null;
        }
    }

    public static final int STRING_VALUE_FIELD_NUMBER = 3;
    /**
     * <pre>
     * Represents a string value.
     * </pre>
     *
     * <code>string string_value = 3;</code>
     * @return Whether the stringValue field is set.
     */
    @Override
    public boolean hasStringValue() {
        return kindCase_ == 3;
    }
    /**
     * <pre>
     * Represents a string value.
     * </pre>
     *
     * <code>string string_value = 3;</code>
     * @return The stringValue.
     */
    @Override
    public String getStringValue() {
        String ref = "";
        if (kindCase_ == 3) {
            ref = (String) kind_;
        }
        return ref;
    }
    /**
     * <pre>
     * Represents a string value.
     * </pre>
     *
     * <code>string string_value = 3;</code>
     * @return The bytes for stringValue.
     */
    @Override
    public ByteString
    getStringValueBytes() {
        String ref = "";
        if (kindCase_ == 3) {
            ref = (String) kind_;
        }
        return ByteString.copyFromUtf8(ref);
    }
    /**
     * <pre>
     * Represents a string value.
     * </pre>
     *
     * <code>string string_value = 3;</code>
     * @param value The stringValue to set.
     */
    private void setStringValue(
            String value) {
        Class<?> valueClass = value.getClass();
        kindCase_ = 3;
        kind_ = value;
    }
    /**
     * <pre>
     * Represents a string value.
     * </pre>
     *
     * <code>string string_value = 3;</code>
     */
    private void clearStringValue() {
        if (kindCase_ == 3) {
            kindCase_ = 0;
            kind_ = null;
        }
    }
    /**
     * <pre>
     * Represents a string value.
     * </pre>
     *
     * <code>string string_value = 3;</code>
     * @param value The bytes for stringValue to set.
     */
    private void setStringValueBytes(
            ByteString value) {
        checkByteStringIsUtf8(value);
        kind_ = value.toStringUtf8();
        kindCase_ = 3;
    }

    public static final int BOOL_VALUE_FIELD_NUMBER = 4;
    /**
     * <pre>
     * Represents a boolean value.
     * </pre>
     *
     * <code>bool bool_value = 4;</code>
     * @return Whether the boolValue field is set.
     */
    @Override
    public boolean hasBoolValue() {
        return kindCase_ == 4;
    }
    /**
     * <pre>
     * Represents a boolean value.
     * </pre>
     *
     * <code>bool bool_value = 4;</code>
     * @return The boolValue.
     */
    @Override
    public boolean getBoolValue() {
        if (kindCase_ == 4) {
            return (Boolean) kind_;
        }
        return false;
    }
    /**
     * <pre>
     * Represents a boolean value.
     * </pre>
     *
     * <code>bool bool_value = 4;</code>
     * @param value The boolValue to set.
     */
    private void setBoolValue(boolean value) {
        kindCase_ = 4;
        kind_ = value;
    }
    /**
     * <pre>
     * Represents a boolean value.
     * </pre>
     *
     * <code>bool bool_value = 4;</code>
     */
    private void clearBoolValue() {
        if (kindCase_ == 4) {
            kindCase_ = 0;
            kind_ = null;
        }
    }

    public static final int STRUCT_VALUE_FIELD_NUMBER = 5;
    /**
     * <pre>
     * Represents a structured value.
     * </pre>
     *
     * <code>.google.protobuf.Struct struct_value = 5;</code>
     */
    @Override
    public boolean hasStructValue() {
        return kindCase_ == 5;
    }
    /**
     * <pre>
     * Represents a structured value.
     * </pre>
     *
     * <code>.google.protobuf.Struct struct_value = 5;</code>
     */
    @Override
    public Struct getStructValue() {
        if (kindCase_ == 5) {
            return (Struct) kind_;
        }
        return Struct.getDefaultInstance();
    }
    /**
     * <pre>
     * Represents a structured value.
     * </pre>
     *
     * <code>.google.protobuf.Struct struct_value = 5;</code>
     */
    private void setStructValue(Struct value) {
        value.getClass();
        kind_ = value;
        kindCase_ = 5;
    }
    /**
     * <pre>
     * Represents a structured value.
     * </pre>
     *
     * <code>.google.protobuf.Struct struct_value = 5;</code>
     */
    private void mergeStructValue(Struct value) {
        value.getClass();
        if (kindCase_ == 5 &&
                kind_ != Struct.getDefaultInstance()) {
            kind_ = Struct.newBuilder((Struct) kind_)
                    .mergeFrom(value).buildPartial();
        } else {
            kind_ = value;
        }
        kindCase_ = 5;
    }
    /**
     * <pre>
     * Represents a structured value.
     * </pre>
     *
     * <code>.google.protobuf.Struct struct_value = 5;</code>
     */
    private void clearStructValue() {
        if (kindCase_ == 5) {
            kindCase_ = 0;
            kind_ = null;
        }
    }

    public static final int LIST_VALUE_FIELD_NUMBER = 6;
    /**
     * <pre>
     * Represents a repeated `Value`.
     * </pre>
     *
     * <code>.google.protobuf.ListValue list_value = 6;</code>
     */
    @Override
    public boolean hasListValue() {
        return kindCase_ == 6;
    }
    /**
     * <pre>
     * Represents a repeated `Value`.
     * </pre>
     *
     * <code>.google.protobuf.ListValue list_value = 6;</code>
     */
    @Override
    public ListValue getListValue() {
        if (kindCase_ == 6) {
            return (ListValue) kind_;
        }
        return ListValue.getDefaultInstance();
    }
    /**
     * <pre>
     * Represents a repeated `Value`.
     * </pre>
     *
     * <code>.google.protobuf.ListValue list_value = 6;</code>
     */
    private void setListValue(ListValue value) {
        value.getClass();
        kind_ = value;
        kindCase_ = 6;
    }
    /**
     * <pre>
     * Represents a repeated `Value`.
     * </pre>
     *
     * <code>.google.protobuf.ListValue list_value = 6;</code>
     */
    private void mergeListValue(ListValue value) {
        value.getClass();
        if (kindCase_ == 6 &&
                kind_ != ListValue.getDefaultInstance()) {
            kind_ = ListValue.newBuilder((ListValue) kind_)
                    .mergeFrom(value).buildPartial();
        } else {
            kind_ = value;
        }
        kindCase_ = 6;
    }
    /**
     * <pre>
     * Represents a repeated `Value`.
     * </pre>
     *
     * <code>.google.protobuf.ListValue list_value = 6;</code>
     */
    private void clearListValue() {
        if (kindCase_ == 6) {
            kindCase_ = 0;
            kind_ = null;
        }
    }

    public static Value parseFrom(
            java.nio.ByteBuffer data)
            throws InvalidProtocolBufferException {
        return GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data);
    }
    public static Value parseFrom(
            java.nio.ByteBuffer data,
            ExtensionRegistryLite extensionRegistry)
            throws InvalidProtocolBufferException {
        return GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Value parseFrom(
            ByteString data)
            throws InvalidProtocolBufferException {
        return GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data);
    }
    public static Value parseFrom(
            ByteString data,
            ExtensionRegistryLite extensionRegistry)
            throws InvalidProtocolBufferException {
        return GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Value parseFrom(byte[] data)
            throws InvalidProtocolBufferException {
        return GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data);
    }
    public static Value parseFrom(
            byte[] data,
            ExtensionRegistryLite extensionRegistry)
            throws InvalidProtocolBufferException {
        return GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Value parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, input);
    }
    public static Value parseFrom(
            java.io.InputStream input,
            ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Value parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static Value parseDelimitedFrom(
            java.io.InputStream input,
            ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Value parseFrom(
            CodedInputStream input)
            throws java.io.IOException {
        return GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, input);
    }
    public static Value parseFrom(
            CodedInputStream input,
            ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
        return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(Value prototype) {
        return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     * `Value` represents a dynamically typed value which can be either
     * null, a number, a string, a boolean, a recursive struct value, or a
     * list of values. A producer of value is expected to set one of these
     * variants. Absence of any variant indicates an error.
     * The JSON representation for `Value` is JSON value.
     * </pre>
     *
     * Protobuf type {@code google.protobuf.Value}
     */
    public static final class Builder extends
            GeneratedMessageLite.Builder<
                    Value, Builder> implements
            // @@protoc_insertion_point(builder_implements:google.protobuf.Value)
            ValueOrBuilder {
        // Construct using com.google.protobuf.Value.newBuilder()
        private Builder() {
            super(DEFAULT_INSTANCE);
        }

        @Override
        public KindCase
        getKindCase() {
            return instance.getKindCase();
        }

        public Builder clearKind() {
            copyOnWrite();
            instance.clearKind();
            return this;
        }


        /**
         * <pre>
         * Represents a null value.
         * </pre>
         *
         * <code>.google.protobuf.NullValue null_value = 1;</code>
         * @return Whether the nullValue field is set.
         */
        @Override
        public boolean hasNullValue() {
            return instance.hasNullValue();
        }
        /**
         * <pre>
         * Represents a null value.
         * </pre>
         *
         * <code>.google.protobuf.NullValue null_value = 1;</code>
         * @return The enum numeric value on the wire for nullValue.
         */
        @Override
        public int getNullValueValue() {
            return instance.getNullValueValue();
        }
        /**
         * <pre>
         * Represents a null value.
         * </pre>
         *
         * <code>.google.protobuf.NullValue null_value = 1;</code>
         * @param value The enum numeric value on the wire for nullValue to set.
         * @return This builder for chaining.
         */
        public Builder setNullValueValue(int value) {
            copyOnWrite();
            instance.setNullValueValue(value);
            return this;
        }
        /**
         * <pre>
         * Represents a null value.
         * </pre>
         *
         * <code>.google.protobuf.NullValue null_value = 1;</code>
         * @return The nullValue.
         */
        @Override
        public NullValue getNullValue() {
            return instance.getNullValue();
        }
        /**
         * <pre>
         * Represents a null value.
         * </pre>
         *
         * <code>.google.protobuf.NullValue null_value = 1;</code>
         * @param value The nullValue to set.
         * @return This builder for chaining.
         */
        public Builder setNullValue(NullValue value) {
            copyOnWrite();
            instance.setNullValue(value);
            return this;
        }
        /**
         * <pre>
         * Represents a null value.
         * </pre>
         *
         * <code>.google.protobuf.NullValue null_value = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearNullValue() {
            copyOnWrite();
            instance.clearNullValue();
            return this;
        }

        /**
         * <pre>
         * Represents a double value.
         * </pre>
         *
         * <code>double number_value = 2;</code>
         * @return Whether the numberValue field is set.
         */
        @Override
        public boolean hasNumberValue() {
            return instance.hasNumberValue();
        }
        /**
         * <pre>
         * Represents a double value.
         * </pre>
         *
         * <code>double number_value = 2;</code>
         * @return The numberValue.
         */
        @Override
        public double getNumberValue() {
            return instance.getNumberValue();
        }
        /**
         * <pre>
         * Represents a double value.
         * </pre>
         *
         * <code>double number_value = 2;</code>
         * @param value The numberValue to set.
         * @return This builder for chaining.
         */
        public Builder setNumberValue(double value) {
            copyOnWrite();
            instance.setNumberValue(value);
            return this;
        }
        /**
         * <pre>
         * Represents a double value.
         * </pre>
         *
         * <code>double number_value = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearNumberValue() {
            copyOnWrite();
            instance.clearNumberValue();
            return this;
        }

        /**
         * <pre>
         * Represents a string value.
         * </pre>
         *
         * <code>string string_value = 3;</code>
         * @return Whether the stringValue field is set.
         */
        @Override
        public boolean hasStringValue() {
            return instance.hasStringValue();
        }
        /**
         * <pre>
         * Represents a string value.
         * </pre>
         *
         * <code>string string_value = 3;</code>
         * @return The stringValue.
         */
        @Override
        public String getStringValue() {
            return instance.getStringValue();
        }
        /**
         * <pre>
         * Represents a string value.
         * </pre>
         *
         * <code>string string_value = 3;</code>
         * @return The bytes for stringValue.
         */
        @Override
        public ByteString
        getStringValueBytes() {
            return instance.getStringValueBytes();
        }
        /**
         * <pre>
         * Represents a string value.
         * </pre>
         *
         * <code>string string_value = 3;</code>
         * @param value The stringValue to set.
         * @return This builder for chaining.
         */
        public Builder setStringValue(
                String value) {
            copyOnWrite();
            instance.setStringValue(value);
            return this;
        }
        /**
         * <pre>
         * Represents a string value.
         * </pre>
         *
         * <code>string string_value = 3;</code>
         * @return This builder for chaining.
         */
        public Builder clearStringValue() {
            copyOnWrite();
            instance.clearStringValue();
            return this;
        }
        /**
         * <pre>
         * Represents a string value.
         * </pre>
         *
         * <code>string string_value = 3;</code>
         * @param value The bytes for stringValue to set.
         * @return This builder for chaining.
         */
        public Builder setStringValueBytes(
                ByteString value) {
            copyOnWrite();
            instance.setStringValueBytes(value);
            return this;
        }

        /**
         * <pre>
         * Represents a boolean value.
         * </pre>
         *
         * <code>bool bool_value = 4;</code>
         * @return Whether the boolValue field is set.
         */
        @Override
        public boolean hasBoolValue() {
            return instance.hasBoolValue();
        }
        /**
         * <pre>
         * Represents a boolean value.
         * </pre>
         *
         * <code>bool bool_value = 4;</code>
         * @return The boolValue.
         */
        @Override
        public boolean getBoolValue() {
            return instance.getBoolValue();
        }
        /**
         * <pre>
         * Represents a boolean value.
         * </pre>
         *
         * <code>bool bool_value = 4;</code>
         * @param value The boolValue to set.
         * @return This builder for chaining.
         */
        public Builder setBoolValue(boolean value) {
            copyOnWrite();
            instance.setBoolValue(value);
            return this;
        }
        /**
         * <pre>
         * Represents a boolean value.
         * </pre>
         *
         * <code>bool bool_value = 4;</code>
         * @return This builder for chaining.
         */
        public Builder clearBoolValue() {
            copyOnWrite();
            instance.clearBoolValue();
            return this;
        }

        /**
         * <pre>
         * Represents a structured value.
         * </pre>
         *
         * <code>.google.protobuf.Struct struct_value = 5;</code>
         */
        @Override
        public boolean hasStructValue() {
            return instance.hasStructValue();
        }
        /**
         * <pre>
         * Represents a structured value.
         * </pre>
         *
         * <code>.google.protobuf.Struct struct_value = 5;</code>
         */
        @Override
        public Struct getStructValue() {
            return instance.getStructValue();
        }
        /**
         * <pre>
         * Represents a structured value.
         * </pre>
         *
         * <code>.google.protobuf.Struct struct_value = 5;</code>
         */
        public Builder setStructValue(Struct value) {
            copyOnWrite();
            instance.setStructValue(value);
            return this;
        }
        /**
         * <pre>
         * Represents a structured value.
         * </pre>
         *
         * <code>.google.protobuf.Struct struct_value = 5;</code>
         */
        public Builder setStructValue(
                Struct.Builder builderForValue) {
            copyOnWrite();
            instance.setStructValue(builderForValue.build());
            return this;
        }
        /**
         * <pre>
         * Represents a structured value.
         * </pre>
         *
         * <code>.google.protobuf.Struct struct_value = 5;</code>
         */
        public Builder mergeStructValue(Struct value) {
            copyOnWrite();
            instance.mergeStructValue(value);
            return this;
        }
        /**
         * <pre>
         * Represents a structured value.
         * </pre>
         *
         * <code>.google.protobuf.Struct struct_value = 5;</code>
         */
        public Builder clearStructValue() {
            copyOnWrite();
            instance.clearStructValue();
            return this;
        }

        /**
         * <pre>
         * Represents a repeated `Value`.
         * </pre>
         *
         * <code>.google.protobuf.ListValue list_value = 6;</code>
         */
        @Override
        public boolean hasListValue() {
            return instance.hasListValue();
        }
        /**
         * <pre>
         * Represents a repeated `Value`.
         * </pre>
         *
         * <code>.google.protobuf.ListValue list_value = 6;</code>
         */
        @Override
        public ListValue getListValue() {
            return instance.getListValue();
        }
        /**
         * <pre>
         * Represents a repeated `Value`.
         * </pre>
         *
         * <code>.google.protobuf.ListValue list_value = 6;</code>
         */
        public Builder setListValue(ListValue value) {
            copyOnWrite();
            instance.setListValue(value);
            return this;
        }
        /**
         * <pre>
         * Represents a repeated `Value`.
         * </pre>
         *
         * <code>.google.protobuf.ListValue list_value = 6;</code>
         */
        public Builder setListValue(
                ListValue.Builder builderForValue) {
            copyOnWrite();
            instance.setListValue(builderForValue.build());
            return this;
        }
        /**
         * <pre>
         * Represents a repeated `Value`.
         * </pre>
         *
         * <code>.google.protobuf.ListValue list_value = 6;</code>
         */
        public Builder mergeListValue(ListValue value) {
            copyOnWrite();
            instance.mergeListValue(value);
            return this;
        }
        /**
         * <pre>
         * Represents a repeated `Value`.
         * </pre>
         *
         * <code>.google.protobuf.ListValue list_value = 6;</code>
         */
        public Builder clearListValue() {
            copyOnWrite();
            instance.clearListValue();
            return this;
        }

        // @@protoc_insertion_point(builder_scope:google.protobuf.Value)
    }
    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
            MethodToInvoke method,
            Object arg0, Object arg1) {
        switch (method) {
            case NEW_MUTABLE_INSTANCE: {
                return new Value();
            }
            case NEW_BUILDER: {
                return new Builder();
            }
            case BUILD_MESSAGE_INFO: {
                Object[] objects = new Object[] {
                        "kind_",
                        "kindCase_",
                        Struct.class,
                        ListValue.class,
                };
                String info =
                        "\u0000\u0006\u0001\u0000\u0001\u0006\u0006\u0000\u0000\u0000\u0001?\u0000\u00023" +
                                "\u0000\u0003\u023b\u0000\u0004:\u0000\u0005<\u0000\u0006<\u0000";
                return newMessageInfo(DEFAULT_INSTANCE, info, objects);
            }
            // fall through
            case GET_DEFAULT_INSTANCE: {
                return DEFAULT_INSTANCE;
            }
            case GET_PARSER: {
                Parser<Value> parser = PARSER;
                if (parser == null) {
                    synchronized (Value.class) {
                        parser = PARSER;
                        if (parser == null) {
                            parser =
                                    new DefaultInstanceBasedParser<Value>(
                                            DEFAULT_INSTANCE);
                            PARSER = parser;
                        }
                    }
                }
                return parser;
            }
            case GET_MEMOIZED_IS_INITIALIZED: {
                return (byte) 1;
            }
            case SET_MEMOIZED_IS_INITIALIZED: {
                return null;
            }
        }
        throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:google.protobuf.Value)
    private static final Value DEFAULT_INSTANCE;
    static {
        Value defaultInstance = new Value();
        // New instances are implicitly immutable so no need to make
        // immutable.
        DEFAULT_INSTANCE = defaultInstance;
        GeneratedMessageLite.registerDefaultInstance(
                Value.class, defaultInstance);
    }

    public static Value getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static volatile Parser<Value> PARSER;

    public static Parser<Value> parser() {
        return DEFAULT_INSTANCE.getParserForType();
    }
}

